### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by break2133** [lvgl/lv_port_win_visual_studio#47]
![87C9AAA6-8EDA-4ed2-B67A-C7B451B0DA4D](https://user-images.githubusercontent.com/75708081/209282685-0da51d6e-27fc-4324-a3b4-f344646e93f9.png)

**Comment by kisvegabor** [comment]
Thank you for pointing it out. I'm sure it was left there by accident. 

It was added in https://github.com/lvgl/lv_port_win_visual_studio/commit/5a44f6408b29751461e4efb266b77babb0c045cb.  @MouriNaruto, could you comment on it?

I've just removed it in https://github.com/lvgl/lv_port_win_visual_studio/commit/75f72844ef0aa9921013c60cb5f83236f7bfef89.

**Comment by MouriNaruto** [comment]
@break2133 @kisvegabor 

> could you comment on it?

I am used to write a “fuck” function with no parameters and "void" return type first before modifying to the definition of new function definition needed because I couldn't think of the correct definition of the function in one breath beforehand. It's a scaffold-like thing which is left accidentally when I am implementing the example of multiple monitor support of win32drv.

I am sorry about that. Thanks @kisvegabor for removing that.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Close issue because this issue should be solved.

Kenji Mouri

**Comment by kisvegabor** [comment]
Sorry for the late reply, I'm still catching up with the emails after the Christmas holiday.

> I will try to use "void test()" instead of "void fuck()" before I modify to the definition of new function definition needed for reducing the similar thing happened. (The similar thing had also been happened in the project which I created, here is the example: https://github.com/M2Team/NanaZip/commit/7149e36809748b4fba40e6ed98a1f335df61b108)

It think it'd be safer, thank you :relaxed:
